### ISSUE TITLE
After winning 50 BiTz, fireworks would not stop

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/bitzxp-dapp#14] opened 2024-06-06 05:27 UTC
After winning 50 BiTz, fireworks would not stop

![image](https://github.com/Itheum/cNFT-gallery/assets/121969933/918bb6eb-bea9-408a-b091-e06631cdad9d)

**Comment by damienen** [comment] 2024-06-06 08:50
Can't reproduce. Closing for now

**Closed as not planned by damienen** 2024-06-06 08:50 UTC
